# Loops

Drawing from Introduction to Programming Logic[@lynne_ohanlon_introduction_2000]
Start with `for` loop as first function term
“Populate an array from a for loop” as an early example; pg 376 blank table with good early exercise.
Side note about infinite loop, importance of settling bounds
What happens if you don’t tell loop to increase?
Examples of `for` loops in multiple languages (Python, C, R)?
To decide: all theory and then all practice, or theory/practice/theory/practice?
Also writing out result of each iteration otherwise you’ll only get the last result (a common problem)

## Exercise - loop trace

Grab a pen and paper and write out the output of each iteration of the loop:

```
for x in 0 to 5 
  write x
  
```
<details>
<summary>Loop output</summary>
1\
2\
3\
4\
5\
</details>\


## Exercise - populate an array

Let's use a `for` loop to populate an array.

We'll start with an empty array called `table` with 4 rows and columns named A, B, C, D, and E:

| A | B | C | D | E |
|---|---|---|---|---|
| &nbsp;  | &nbsp;  | &nbsp;  | &nbsp;  | &nbsp;  |
| &nbsp;  | &nbsp;  | &nbsp;  | &nbsp;  | &nbsp;  |
| &nbsp;  | &nbsp;  | &nbsp;  | &nbsp;  | &nbsp;  |
| &nbsp;  | &nbsp;  | &nbsp;  | &nbsp;  | &nbsp;  |

We want to populate this table with numbers, starting with 1 and increasing sequentially (1, 2, 3, 4, etc.). We want to fill each row completely before moving on to start filling the next row.

Our `for` loop:

__[[adapt programming logic book exercise for loop]]__
    

Grab and pen and paper (or a spreadsheet program like Google Sheets or Excel) and manually fill in the empty cells in the array.

- What is the number in cell A1?
- What is the number in cell B2?
- What is the number in cell D4?

<details>
<summary>Your filled array should look like this</summary>

| A   | B   | C   | D   | E  |
|---  |---  |---  |---  |--- |
| 1   |  2  | 3   |  4  | 5  |
| 6   |  7  | 8   |  9  | 10 |
| 11  | 12  | 13  | 14  | 15 |
| 16  | 17  | 18  | 19  | 20 |

</details>


## Other Types of Loops 

There are other types of loops in addition to the commonly used `for` loop.\ 

The `while` loop uses a condition at the start of the loop to determine, in advance, when the loop will stop. For example, recall the initial for loop:

```
for x in 0 to 5 
  write x
  
```

An equivalent `while` loop would look like:

```


```

Another type of loop is a `do while` loop (check at end) and an `until` loop (check at end).

```

```

```

```

## Caveats

Loops are a frequently encountered concept in programming and come with their own set of common issues.

### Infinite loops

When condition is never false or otherwise has no break

### Overwriting outputs

```
for x in 0 to 5 
  answer = x

write answer
  
```




