# Flextables

This reflects nested for loops of `row+column`

```{r test-area, echo = FALSE, message=FALSE}
library(flextable)
library(officer)
library(shiny)
library(dplyr)

# reference: https://davidgohel.github.io/flextable/reference/bg.html

num_rows = 4
num_col = 5
row_names <- list()

matrix_demo <- matrix(nrow=num_rows, ncol = num_col)
for (i in 1:num_rows){
  row_names[i] <- paste0("Row ",i)
  for (j in 1:num_col){
    matrix_demo[i,j] <- i+j
  }# end j for loop
}# end i for loop

col_names <- list()
for (j in 1:(num_col)){
  col_names[j] <- paste0("Column ",j)
}
col_names <- c("Index", col_names)

table_demo <-   data.frame(index = unlist(row_names),
                         j1 = matrix_demo[,1],
                         j2 = matrix_demo[,2],
                         j3 = matrix_demo[,3],
                         j4 = matrix_demo[,4],
                         j5 = matrix_demo[,5]
                         )
colnames(table_demo) <- col_names

big_border = fp_border(color="black", width = 2)
small_border = fp_border(color="black", width = 1)

ft <- flextable(table_demo) %>% 
      border_remove() %>%
      border_outer(part="all", border = big_border ) %>%
      border_inner_h(part="all", border = small_border ) %>% 
      border_inner_v(part="all", border = small_border ) %>% 
      align(align = "center", part = "all") %>%
      bg(j="Index", bg="gray90", part="body") %>%
      bg(bg="gray90", part="header") %>%
      vline(j="Index", border = big_border, part = "all")
ft 
```

This reflects nested for loops of `(5*(row-1))+column`

```{r test-area2, echo = FALSE}
library(flextable)
library(officer)
library(shiny)
library(dplyr)

# reference: https://davidgohel.github.io/flextable/reference/bg.html

num_rows = 5
num_col = 5
row_names <- list()
matrix_demo <- matrix(nrow=num_rows, ncol = num_col)
for (i in 1:num_rows){
  row_names[i] <- paste0("Row ",i)
  for (j in 1:num_col){
    matrix_demo[i,j] <- (5*(i-1))+j
  }# end j for loop
}# end i for loop

col_names <- list()
for (j in 1:(num_col)){
  col_names[j] <- paste0("Column ",j)
}
col_names <- c("Index", col_names)


table_demo <-   data.frame(index = unlist(row_names),
                         j1 = matrix_demo[,1],
                         j2 = matrix_demo[,2],
                         j3 = matrix_demo[,3],
                         j4 = matrix_demo[,4],
                         j5 = matrix_demo[,5]
                         )

colnames(table_demo) <- col_names

# print(table_demo)

big_border = fp_border(color="black", width = 2)
small_border = fp_border(color="black", width = 1)

ft <- flextable(table_demo) %>% 
      border_remove() %>%
      border_outer(part="all", border = big_border ) %>%
      border_inner_h(part="all", border = small_border ) %>% 
      border_inner_v(part="all", border = small_border ) %>% 
      align(align = "center", part = "all") %>%
      bg(j="Index", bg="gray90", part="body") %>%
      bg(bg="gray90", part="header") %>%
      vline(j="Index", border = big_border, part = "all")
ft 
```
